### ISSUE TITLE
New filenames

### ISSUE THREAD

**Issue by Cold-D** [aldomann/telegram-systray-icons#1]
Hi,
I've just noticed that the icon in the system tray has been reset to the default after update Telegram.
Here's the changes in 1.5.7 Beta:
https://github.com/telegramdesktop/tdesktop/commit/3e7a688811e293e837497512a5d71ab839635f51

Could you rename the files or create symlinks for them?

**Comment by aldomann** [comment]
Thanks for reporting, man. 
Actually, the repository has been migrated to GitLab, where I keep the latest version: https://gitlab.com/aldomann/telegram-systray-icons (I will add this on the README file).

It is true as you say, however, that the icons have been renamed, I need to fix that.

Could you confirm, however if in your system the icons are located either in 
- `~/.local/share/TelegramDesktop/tdata/ticons` (as I understand, the new location, changed about 3 or 4 months ago) 
- or `~/./TelegramDesktop/tdata/ticons` (presumably, the old location).

I'm saying this because, if you keep your system updated, you should have had missing icons a long time before. If you haven't I'm thinking that different distros have different paths for storing the `tdata` settings.

**Comment by Cold-D** [comment]
Thanks for the reply.
I'm using Fedora 29. The path is `~/.local/share/TelegramDesktop/tdata/ticons`.
I guess it was always the same in Fedora, so no problems here.

**Comment by alxlg** [comment]
In file names "ico" must be replaced by "icon", for example `icon_22_1.png`

**Comment by aldomann** [comment]
This has been solved in the latest commit on the [GitLab repository](https://gitlab.com/aldomann/telegram-systray-icons/commit/06596ca58ab31c766c2d8cc640984ceac2161920).

Sorry for taking so long, I wanted to actually redo the rendering process of the icons and introduce new icon options, but that will take longer than expected.
